FROM mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.1-cudnn7-ubuntu18.04
RUN apt-get update
RUN apt-get install 'ffmpeg' 'libsm6' 'libxext6'  -y
RUN conda install -c r -y conda python=3.6.2 pip=20.1.1
RUN pip install torch==1.5 torchvision==0.6
RUN pip install cython pyyaml==5.1
RUN pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI' --ignore-installed certifi
RUN python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
RUN pip install opencv-python 
RUN conda install jupyterlab
RUN conda install nb_conda_kernels
RUN conda install scikit-learn
RUN pip install --upgrade azureml-sdk[notebooks]
RUN pip install azureml-datadrift
RUN pip install azureml-train-automl
RUN pip install azureml-interpret
RUN pip install imagecorruptions
RUN pip install imgaug
RUN conda install lxml
RUN pip install adabound
RUN pip install azureml-contrib-services
RUN conda install jsonpickle
