FROM mcr.microsoft.com/azureml/base-gpu:openmpi3.1.2-cuda10.1-cudnn7-ubuntu18.04
RUN conda create --name trident
RUN conda install -n trident pip
RUN pip install --upgrade pip
RUN pip install torch==1.5 torchvision==0.6 
RUN pip install cython pyyaml==5.1
RUN pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI' --ignore-installed certifi
RUN python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
RUN pip install opencv-python 
RUN conda install -n trident jupyterlab
RUN conda install -n trident nb_conda_kernels
RUN conda install -n trident scikit-learn
RUN conda install -n trident seaborn
RUN pip install --upgrade azureml-sdk[automl,datadrift,interpret,notebooks]
RUN pip install imgaug
COPY ./dev_packages /
RUN pip install pascal-voc-writer
RUN pip install azureml-contrib-services
