# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"register_dataset_from_file": "00_detectron2_utilities.ipynb",
         "register_dataset_from_dicts": "00_detectron2_utilities.ipynb",
         "create_detectron2_dicts": "00_detectron2_utilities.ipynb",
         "evaluate_dicts": "00_detectron2_utilities.ipynb",
         "evaluate_dataloader_item": "00_detectron2_utilities.ipynb",
         "dummy_detectron2_result": "00_detectron2_utilities.ipynb",
         "combine_tile_annotations": "01_tiling.ipynb",
         "save_annotated_image": "00_detectron2_utilities.ipynb",
         "save_annotated_images": "00_detectron2_utilities.ipynb",
         "write_results_to_xml": "00_detectron2_utilities.ipynb",
         "read_in_predictions": "00_detectron2_utilities.ipynb",
         "calc_padding_for_fpad": "01_tiling.ipynb",
         "get_tiles": "01_tiling.ipynb",
         "tile_images": "01_tiling.ipynb",
         "get_tile_offsets": "01_tiling.ipynb",
         "build_augmentation": "02_custom_model.ipynb",
         "RandomCorruption": "02_custom_model.ipynb",
         "TridentDatasetMapper": "02_custom_model.ipynb",
         "TileDatasetMapper": "02_custom_model.ipynb",
         "IterableTileDataset": "02_custom_model.ipynb",
         "build_train_loader": "02_custom_model.ipynb",
         "JTFMEvaluator": "02_custom_model.ipynb",
         "Trainer": "02_custom_model.ipynb",
         "JP_RepeatFactorTrainingSampler": "02_custom_model.ipynb",
         "nostdout": "06_utilities.ipynb",
         "path_insensitive": "06_utilities.ipynb",
         "get_files": "06_utilities.ipynb",
         "find_imagepath_from_stem": "06_utilities.ipynb",
         "get_image_size": "06_utilities.ipynb",
         "write_list_to_file": "06_utilities.ipynb",
         "sample_file": "06_utilities.ipynb",
         "write_object_to_file": "06_utilities.ipynb",
         "load_object_from_file": "06_utilities.ipynb",
         "split_by_random": "06_utilities.ipynb",
         "write_train_validate_files": "06_utilities.ipynb",
         "LabelFixer": "06_utilities.ipynb",
         "convert_xml_labels_to_csv": "06_utilities.ipynb",
         "count_classes": "06_utilities.ipynb",
         "get_one_batch": "06_utilities.ipynb",
         "get_dataloader_item": "06_utilities.ipynb",
         "save_tensor_to_csv": "06_utilities.ipynb",
         "display_tensor": "06_utilities.ipynb",
         "cv2_imshow": "06_utilities.ipynb",
         "preds_per_cat": "06_utilities.ipynb",
         "falsepositives_per_cat": "06_utilities.ipynb",
         "write_xml_for_fullimage": "06_utilities.ipynb",
         "describe_image": "06_utilities.ipynb",
         "fullsize_stats": "06_utilities.ipynb",
         "PascalVocWriter": "06_utilities.ipynb",
         "PascalVocReader": "06_utilities.ipynb",
         "reorder_paired_lists": "06_utilities.ipynb"}

modules = ["detectron2_utilities.py",
           "tiling.py",
           "model.py",
           "utilities.py"]

doc_url = "localhost/trident_dev/"

git_url = "https://github.com/jcpayne/trident_dev/tree/master/"

def custom_doc_links(name): return None
